### ISSUE TITLE
rake failed. Is project alive?

### ISSUE THREAD

**Issue by slayer** [monkrb/monk#6]
As I see 2 years without update

I have installed fresh ruby 1.9, and monk, but rake tests fails:

```
    master vlad@pant ~/dev/vx/back $ rake
    (in /home/vlad/dev/vx/back)
    /home/vlad/dev/vx/back/vendor/quietbacktrace-0.1.1/lib/quietbacktrace.rb:153:in `<top (required)>': uninitialized constant Test::Unit::Util (NameError)
            from /home/vlad/.rbenv/versions/1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
            from /home/vlad/.rbenv/versions/1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
            from /home/vlad/dev/vx/back/test/test_helper.rb:8:in `<top (required)>'
            from /home/vlad/.rbenv/versions/1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
            from /home/vlad/.rbenv/versions/1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
            from test/routes/css_test.rb:1:in `<top (required)>'
            from /home/vlad/dev/vx/back/Thorfile:11:in `load'
            from /home/vlad/dev/vx/back/Thorfile:11:in `block in test'
            from /home/vlad/dev/vx/back/Thorfile:10:in `each'
            from /home/vlad/dev/vx/back/Thorfile:10:in `test'
```

**Comment by djanowski** [comment]
I think it's pretty dead :)

**Comment by soveran** [comment]
We have been using Cuba for a while now (http://cuba.is). That said, if you are interested in Monk I can fix that error by getting rid of the stories gem, which is not compatible with minitest (test/unit in 1.9.x).

**Comment by slayer** [comment]
Thanks, dont worry. I have switched to padrino. Thanks for link to cuba.
